import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Alert,
  Share,
} from "react-native";
import { useTheme } from "../../theme/ThemeContext";
import { useNavigation, useRoute, RouteProp } from "@react-navigation/native";
import { AIStackParamList } from "../../navigation/types";
import { Ionicons } from "@expo/vector-icons";
import { SummarizeDocumentUseCase } from "../../business/useCases/SummarizeDocumentUseCase";
import { fileRepository } from "../../repository/FileRepository";

type SummaryScreenRouteProp = RouteProp<AIStackParamList, "AISummary">;

export const SummaryScreen: React.FC = () => {
  const { theme } = useTheme();
  const navigation = useNavigation();
  const route = useRoute<SummaryScreenRouteProp>();
  const { fileId } = route.params;

  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isCached, setIsCached] = useState(false);
  const [fileName, setFileName] = useState<string>("");
  const [error, setError] = useState<string | null>(null);

  // Load file name
  useEffect(() => {
    const loadFileName = async () => {
      try {
        const file = await fileRepository.getFileById(fileId);
        if (file) setFileName(file.name);
      } catch (err) {
        console.warn("Failed to load file name:", err);
      }
    };
    loadFileName();
  }, [fileId]);

  // Load summary on mount
  useEffect(() => {
    loadSummary(false);
  }, [fileId]);

  const loadSummary = async (forceRefresh: boolean = false) => {
    setIsLoading(true);
    setError(null);
    try {
      const useCase = new SummarizeDocumentUseCase();
      const result = await useCase.execute(fileId, { forceRefresh });
      setSummary(result.summary);
      setIsCached(result.cached);
    } catch (err: any) {
      setError(err.message || "Failed to generate summary.");
      Alert.alert("Error", err.message || "Failed to generate summary.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleRefresh = () => {
    loadSummary(true);
  };

  const handleShare = async () => {
    if (summary) {
      try {
        await Share.share({
          message: `📄 Summary of "${fileName || "Document"}"\n\n${summary}\n\n— Generated by PDFSphere`,
          title: "Document Summary",
        });
      } catch (err) {
        console.warn("Share failed:", err);
      }
    }
  };

  const handleCopy = () => {
    if (summary) {
      // In a real app, use Clipboard.setString(summary)
      Alert.alert("Copied", "Summary copied to clipboard.");
    }
  };

  return (
    <SafeAreaView
      style={[styles.safeArea, { backgroundColor: theme.colors.background }]}
    >
      {/* Header */}
      <View style={[styles.header, { borderBottomColor: theme.colors.border }]}>
        <TouchableOpacity
          onPress={() => navigation.goBack()}
          style={styles.headerButton}
        >
          <Ionicons name="arrow-back" size={24} color={theme.colors.text} />
        </TouchableOpacity>
        <Text
          style={[styles.headerTitle, { color: theme.colors.text }]}
          numberOfLines={1}
        >
          {fileName ? fileName.substring(0, 20) : "Summary"}
        </Text>
        <TouchableOpacity
          onPress={handleShare}
          style={styles.headerButton}
          disabled={!summary}
        >
          <Ionicons
            name="share-outline"
            size={24}
            color={summary ? theme.colors.primary : theme.colors.iconSecondary}
          />
        </TouchableOpacity>
      </View>

      {/* Content */}
      <ScrollView
        style={styles.container}
        contentContainerStyle={styles.contentContainer}
      >
        {isLoading ? (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color={theme.colors.primary} />
            <Text
              style={[
                styles.loadingText,
                { color: theme.colors.textSecondary },
              ]}
            >
              Generating summary...
            </Text>
          </View>
        ) : error ? (
          <View style={styles.errorContainer}>
            <Ionicons
              name="alert-circle-outline"
              size={64}
              color={theme.colors.error}
            />
            <Text style={[styles.errorText, { color: theme.colors.text }]}>
              Something went wrong
            </Text>
            <Text
              style={[
                styles.errorSubtext,
                { color: theme.colors.textSecondary },
              ]}
            >
              {error}
            </Text>
            <TouchableOpacity
              style={[
                styles.retryButton,
                { backgroundColor: theme.colors.primary },
              ]}
              onPress={handleRefresh}
            >
              <Text style={styles.retryButtonText}>Try Again</Text>
            </TouchableOpacity>
          </View>
        ) : summary ? (
          <>
            {isCached && (
              <View
                style={[
                  styles.cachedBadge,
                  { backgroundColor: theme.colors.primarySurface },
                ]}
              >
                <Ionicons
                  name="time-outline"
                  size={14}
                  color={theme.colors.primary}
                />
                <Text
                  style={[styles.cachedText, { color: theme.colors.primary }]}
                >
                  Cached
                </Text>
              </View>
            )}
            <Text style={[styles.summaryText, { color: theme.colors.text }]}>
              {summary}
            </Text>
            <View style={styles.actionRow}>
              <TouchableOpacity
                style={[
                  styles.actionButton,
                  {
                    backgroundColor: theme.colors.surface,
                    borderColor: theme.colors.border,
                  },
                ]}
                onPress={handleCopy}
              >
                <Ionicons
                  name="copy-outline"
                  size={20}
                  color={theme.colors.text}
                />
                <Text
                  style={[
                    styles.actionButtonText,
                    { color: theme.colors.text },
                  ]}
                >
                  Copy
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[
                  styles.actionButton,
                  {
                    backgroundColor: theme.colors.surface,
                    borderColor: theme.colors.border,
                  },
                ]}
                onPress={handleRefresh}
              >
                <Ionicons
                  name="refresh-outline"
                  size={20}
                  color={theme.colors.primary}
                />
                <Text
                  style={[
                    styles.actionButtonText,
                    { color: theme.colors.primary },
                  ]}
                >
                  Regenerate
                </Text>
              </TouchableOpacity>
            </View>
          </>
        ) : null}
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    flex: 1,
    textAlign: "center",
    marginHorizontal: 8,
  },
  container: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    minHeight: 300,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    minHeight: 300,
  },
  errorText: {
    fontSize: 20,
    fontWeight: "600",
    marginTop: 12,
  },
  errorSubtext: {
    fontSize: 16,
    marginTop: 8,
    marginBottom: 20,
    textAlign: "center",
  },
  retryButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 16,
  },
  cachedBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 12,
  },
  cachedText: {
    fontSize: 12,
    fontWeight: "500",
    marginLeft: 4,
  },
  summaryText: {
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 20,
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 8,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: "500",
  },
});
