import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Alert,
  Modal,
  Share,
} from "react-native";
import { useTheme } from "../../theme/ThemeContext";
import { useRoute, useNavigation, RouteProp } from "@react-navigation/native";
import { AIStackParamList } from "../../navigation/types";
import { Ionicons } from "@expo/vector-icons";
import { TranslateDocumentUseCase } from "../../business/useCases/TranslateDocumentUseCase";
import { fileRepository } from "../../repository/FileRepository";

type TranslationScreenRouteProp = RouteProp<AIStackParamList, "AITranslate">;

const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "ur", label: "Urdu" },
  { code: "ar", label: "Arabic" },
  { code: "hi", label: "Hindi" },
  { code: "fr", label: "French" },
  { code: "es", label: "Spanish" },
  { code: "de", label: "German" },
  { code: "zh", label: "Chinese" },
  { code: "ja", label: "Japanese" },
  { code: "ko", label: "Korean" },
  { code: "pt", label: "Portuguese" },
  { code: "ru", label: "Russian" },
];

export const TranslationScreen: React.FC = () => {
  const { theme } = useTheme();
  const navigation = useNavigation();
  const route = useRoute<TranslationScreenRouteProp>();
  const { fileId } = route.params;

  const [selectedLanguage, setSelectedLanguage] = useState("en");
  const [translation, setTranslation] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isCached, setIsCached] = useState(false);
  const [showLanguagePicker, setShowLanguagePicker] = useState(false);
  const [fileName, setFileName] = useState<string>("");
  const [error, setError] = useState<string | null>(null);

  // Load file name
  useEffect(() => {
    const loadFileName = async () => {
      try {
        const file = await fileRepository.getFileById(fileId);
        if (file) setFileName(file.name);
      } catch (err) {
        console.warn("Failed to load file name:", err);
      }
    };
    loadFileName();
  }, [fileId]);

  // Load translation when file or language changes
  useEffect(() => {
    if (fileId && selectedLanguage) {
      translateDocument(false);
    }
  }, [fileId, selectedLanguage]);

  const translateDocument = async (forceRefresh: boolean = false) => {
    setIsLoading(true);
    setError(null);
    try {
      const useCase = new TranslateDocumentUseCase();
      const result = await useCase.execute(
        fileId,
        selectedLanguage,
        forceRefresh,
      );
      setTranslation(result);
      setIsCached(!forceRefresh); // if not forced, it might be cached
    } catch (err: any) {
      setError(err.message || "Translation failed.");
      Alert.alert("Error", err.message || "Translation failed.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleLanguageSelect = (code: string) => {
    setSelectedLanguage(code);
    setShowLanguagePicker(false);
  };

  const handleShare = async () => {
    if (translation) {
      try {
        await Share.share({
          message: `🌐 Translation of "${fileName || "Document"}" to ${LANGUAGES.find((l) => l.code === selectedLanguage)?.label}\n\n${translation}\n\n— Generated by PDFSphere`,
          title: "Document Translation",
        });
      } catch (err) {
        console.warn("Share failed:", err);
      }
    }
  };

  const handleCopy = () => {
    if (translation) {
      // In a real app, use Clipboard.setString(translation)
      Alert.alert("Copied", "Translation copied to clipboard.");
    }
  };

  const selectedLanguageLabel =
    LANGUAGES.find((l) => l.code === selectedLanguage)?.label || "Select";

  return (
    <SafeAreaView
      style={[styles.safeArea, { backgroundColor: theme.colors.background }]}
    >
      {/* Header */}
      <View style={[styles.header, { borderBottomColor: theme.colors.border }]}>
        <TouchableOpacity
          onPress={() => navigation.goBack()}
          style={styles.headerButton}
        >
          <Ionicons name="arrow-back" size={24} color={theme.colors.text} />
        </TouchableOpacity>
        <Text
          style={[styles.headerTitle, { color: theme.colors.text }]}
          numberOfLines={1}
        >
          {fileName ? fileName.substring(0, 20) : "Translation"}
        </Text>
        <TouchableOpacity
          onPress={handleShare}
          style={styles.headerButton}
          disabled={!translation}
        >
          <Ionicons
            name="share-outline"
            size={24}
            color={
              translation ? theme.colors.primary : theme.colors.iconSecondary
            }
          />
        </TouchableOpacity>
      </View>

      {/* Language Selector */}
      <View
        style={[
          styles.languageSelector,
          { borderBottomColor: theme.colors.border },
        ]}
      >
        <Text
          style={[styles.languageLabel, { color: theme.colors.textSecondary }]}
        >
          Target Language:
        </Text>
        <TouchableOpacity
          style={[
            styles.languagePicker,
            {
              backgroundColor: theme.colors.surface,
              borderColor: theme.colors.border,
            },
          ]}
          onPress={() => setShowLanguagePicker(true)}
        >
          <Text
            style={[styles.languagePickerText, { color: theme.colors.text }]}
          >
            {selectedLanguageLabel}
          </Text>
          <Ionicons
            name="chevron-down"
            size={20}
            color={theme.colors.iconSecondary}
          />
        </TouchableOpacity>
      </View>

      {/* Content */}
      <ScrollView
        style={styles.container}
        contentContainerStyle={styles.contentContainer}
      >
        {isLoading ? (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color={theme.colors.primary} />
            <Text
              style={[
                styles.loadingText,
                { color: theme.colors.textSecondary },
              ]}
            >
              Translating to {selectedLanguageLabel}...
            </Text>
          </View>
        ) : error ? (
          <View style={styles.errorContainer}>
            <Ionicons
              name="alert-circle-outline"
              size={64}
              color={theme.colors.error}
            />
            <Text style={[styles.errorText, { color: theme.colors.text }]}>
              Translation failed
            </Text>
            <Text
              style={[
                styles.errorSubtext,
                { color: theme.colors.textSecondary },
              ]}
            >
              {error}
            </Text>
            <TouchableOpacity
              style={[
                styles.retryButton,
                { backgroundColor: theme.colors.primary },
              ]}
              onPress={() => translateDocument(true)}
            >
              <Text style={styles.retryButtonText}>Retry</Text>
            </TouchableOpacity>
          </View>
        ) : translation ? (
          <>
            {isCached && (
              <View
                style={[
                  styles.cachedBadge,
                  { backgroundColor: theme.colors.primarySurface },
                ]}
              >
                <Ionicons
                  name="time-outline"
                  size={14}
                  color={theme.colors.primary}
                />
                <Text
                  style={[styles.cachedText, { color: theme.colors.primary }]}
                >
                  Cached
                </Text>
              </View>
            )}
            <Text
              style={[styles.translationText, { color: theme.colors.text }]}
            >
              {translation}
            </Text>
            <View style={styles.actionRow}>
              <TouchableOpacity
                style={[
                  styles.actionButton,
                  {
                    backgroundColor: theme.colors.surface,
                    borderColor: theme.colors.border,
                  },
                ]}
                onPress={handleCopy}
              >
                <Ionicons
                  name="copy-outline"
                  size={20}
                  color={theme.colors.text}
                />
                <Text
                  style={[
                    styles.actionButtonText,
                    { color: theme.colors.text },
                  ]}
                >
                  Copy
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[
                  styles.actionButton,
                  {
                    backgroundColor: theme.colors.surface,
                    borderColor: theme.colors.border,
                  },
                ]}
                onPress={() => translateDocument(true)}
              >
                <Ionicons
                  name="refresh-outline"
                  size={20}
                  color={theme.colors.primary}
                />
                <Text
                  style={[
                    styles.actionButtonText,
                    { color: theme.colors.primary },
                  ]}
                >
                  Retranslate
                </Text>
              </TouchableOpacity>
            </View>
          </>
        ) : null}
      </ScrollView>

      {/* Language Picker Modal */}
      <Modal visible={showLanguagePicker} transparent animationType="slide">
        <View
          style={[styles.modalOverlay, { backgroundColor: "rgba(0,0,0,0.5)" }]}
        >
          <View
            style={[
              styles.modalContainer,
              { backgroundColor: theme.colors.surface },
            ]}
          >
            <View
              style={[
                styles.modalHeader,
                { borderBottomColor: theme.colors.border },
              ]}
            >
              <Text style={[styles.modalTitle, { color: theme.colors.text }]}>
                Select Language
              </Text>
              <TouchableOpacity onPress={() => setShowLanguagePicker(false)}>
                <Ionicons name="close" size={24} color={theme.colors.text} />
              </TouchableOpacity>
            </View>
            <ScrollView style={styles.modalList}>
              {LANGUAGES.map((lang) => (
                <TouchableOpacity
                  key={lang.code}
                  style={[
                    styles.modalItem,
                    selectedLanguage === lang.code && {
                      backgroundColor: theme.colors.primarySurface,
                    },
                  ]}
                  onPress={() => handleLanguageSelect(lang.code)}
                >
                  <Text
                    style={[styles.modalItemText, { color: theme.colors.text }]}
                  >
                    {lang.label}
                  </Text>
                  {selectedLanguage === lang.code && (
                    <Ionicons
                      name="checkmark"
                      size={20}
                      color={theme.colors.primary}
                    />
                  )}
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>
        </View>
      </Modal>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    flex: 1,
    textAlign: "center",
    marginHorizontal: 8,
  },
  languageSelector: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  languageLabel: {
    fontSize: 16,
    marginRight: 12,
  },
  languagePicker: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
  },
  languagePickerText: {
    fontSize: 16,
    marginRight: 8,
  },
  container: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    minHeight: 300,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    minHeight: 300,
  },
  errorText: {
    fontSize: 20,
    fontWeight: "600",
    marginTop: 12,
  },
  errorSubtext: {
    fontSize: 16,
    marginTop: 8,
    marginBottom: 20,
    textAlign: "center",
  },
  retryButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 16,
  },
  cachedBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 12,
  },
  cachedText: {
    fontSize: 12,
    fontWeight: "500",
    marginLeft: 4,
  },
  translationText: {
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 20,
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 8,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: "500",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "85%",
    maxHeight: "70%",
    padding: 20,
    borderRadius: 16,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 12,
    borderBottomWidth: 1,
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
  },
  modalList: {
    maxHeight: 400,
  },
  modalItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  modalItemText: {
    fontSize: 16,
  },
});
